---
name: CI
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for publishing to JSR
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          install: true

      - name: Build
        run: pnpm build

      - name: Type Check
        run: pnpm run typecheck

      - name: Tests
        run: pnpm run test

      - name: Lint
        run: pnpm run lint

      - name: Format
        run: pnpm run format:check

      - name: Dry Run Publish on NPM
        # "github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')"
        if: false
        run: pnpm stage publish --provenance --access public --dry-run --no-git-checks

      - name: Dry Run Publish on JSR
        run: pnpx jsr publish --dry-run

      - name: Publish on NPM
        if: "startsWith(github.ref, 'refs/tags/')"
        run: pnpm stage publish --provenance --access public --no-git-checks

      - name: Publish on JSR
        if: "startsWith(github.ref, 'refs/tags/')"
        run: pnpx jsr publish
