---
name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"

      - name: Enable PNPM
        run: corepack enable pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Dry Run Publish on NPM
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: pnpm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Dry Run Publish on JSR
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: npx jsr publish --dry-run

      - name: Publish on NPM
        if: startsWith(github.ref, 'refs/tags/')
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish on JSR
        if: startsWith(github.ref, 'refs/tags/')
        run: pnpx jsr publish
