---
name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"

      - name: Enable PNPM
        run: corepack enable pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish on NPM
        run: pnpm publish --access public
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish on JSR
        if: startsWith(github.ref, 'refs/tags/')
        run: npx jsr publish